### ISSUE TITLE
Explanations and Requests

### ISSUE THREAD

**Issue by kg86** [suffixsorting/suffixsorting.github.io#1]
Hello, the masters of this repository.

I am Keisuke Goto who was referred to in your document. I read your document, but I must say that some of the claims are incorrect. I have written an explanation of what happened in the
[link](https://github.com/kg86/sa-comment), and would very much like for you to read it.

I would like to request the following

- Please remove this document. Some of the claims are incorrect, and damages my reputation.
- If you do not accept the first request, please put the link to my claims in your document so that readers can see both claims.

**Comment by kg86** [comment]
I should have mentioned to @suffixsorting.

**Comment by suffixsorting** [comment]
We emphasize that we are right. We also updated our document to add his link.
